### ISSUE TITLE
과제 피드백

### ISSUE THREAD

**Issue by jeongmin-dev** [SoJaeBeom/react-sns-project#17]
- 상태관리가 잘 되어 있나요? (유지/초기화)
axios와 리덕스를 잘 사용하였는데 보통은 reducers 안에 상태값을 저장하는 것이 좋습니다. 특별한 Pending과 fullfilled 액션이 있을 때 extraReducers를 사용해 주세요.

- 각 컴포넌트의 재사용성이 높은가요?
컴포넌트들의 재사용성을 고려한 흔적이 잘 보입니다! 공통으로 사용되는 요소들을 따로 빼서 컴포넌트화 시키면 재사용성이 높아질 거에요!
아래의 키워드를 공부해 볼 것을 권장합니다.
atomic design react

- 그 외
사용하지 않는 styled-component 선언은 지워주세요!

궁금한 사항은 댓글로 남겨주세요

**Comment by SoJaeBeom** [comment]
1번에 답변해주신 내용이 잘 이해가 되지 않아서요.

관련 내용에 대해 검색해 볼 키워드나 참고 자료가 있을까요? 
아니면 다시 추가 설명을 부탁드려도 될까요?

**Comment by jeongmin-dev** [comment]
아! 답변을 늦게 드려 죄송해요!
현재 thunk를 사용중이셔서 1번 부분은 제외하셔도 되지만 thunkapi가 아닌 함수나 콜백함수를 사용하셔야 하는 경우엔 (dispatch)
리듀서에서 작성하는것을 원칙으로 하고 있습니다!
thunkApi = extraReducers / dispatch 혹은 함수 사용 시 = reducers
!! fullfilled 부분에서 api 통신 성공 시의 값을 저장하고 있고 혹여나 컴포넌트에서 pending이나 reject에 대한 상태값이 없다면 굳이 작성을 안하셔도 됩니다!

과제 하시는데 혼선을 드려 죄송합니다.
